### PR TITLE
Which key restart ide

### PR DESCRIPTION
**Pull request by sweetliquid**
## Description
Please explain the changes you made here.

## Checklist
- [x] I have read
[CONTRIBUTING](https://github.com/MarcoIeni/intellimacs/blob/master/docs/CONTRIBUTING.org)
guidelines.

#### [CHANGELOG](https://github.com/MarcoIeni/intellimacs/blob/master/docs/CHANGELOG.org):
- [ ] Updated
- [ ] I will update it after this PR has been discussed
- [ ] No need to update

#### [KEYBINDINGS](https://github.com/MarcoIeni/intellimacs/blob/master/docs/KEYBINDINGS.org):
- [x] Updated
- [ ] I will update it after this PR has been discussed
- [ ] No need to update

#### [PLUGINS](https://github.com/MarcoIeni/intellimacs/blob/master/docs/PLUGINS.org):
- [ ] Updated
- [ ] I will update it after this PR has been discussed
- [x] No need to update

### CODE REVIEW

**Comment by marcoieni** [comment]
Great! What do you think about using this action as `spc q r` instead of `spc q R` and moving `InvalidateCache` to `spc q R`

i.e.

```
let g:WhichKeyDesc_Quit_InvalidateCache = "<leader>qR invalidate-cache"
nnoremap <leader>qR    :action InvalidateCaches<CR>
vnoremap <leader>qR    <Esc>:action InvalidateCaches<CR>
let g:WhichKeyDesc_Quit_Restart = "<leader>qr restart"
nnoremap <leader>qr    :action RestartIde<CR>
vnoremap <leader>qr    <Esc>:action RestartIde<CR>
```

**Comment by sweetliquid** [comment]
Please Take A Look

**Comment by marcoieni** [comment]
Awesome! can you update [CHANGELOG](https://github.com/MarcoIeni/intellimacs/blob/master/docs/CHANGELOG.org) and [KEYBINDINGS](https://github.com/MarcoIeni/intellimacs/blob/master/docs/KEYBINDINGS.org), too?

In changelog I would say that now `spc q r` just restarts the IDE without invalidating the cache, too.

While in keybindings I would change `spc q R` to `Invalidate cache`.

What do you think? Tell me if you have some doubts. Thanks.

**Comment by marcoieni** [comment]
Also, can you rename the PR to something more meaningful? Because that will be the commit message.

**Comment by sweetliquid** [comment]
That's great, can you please review again?

**Comment by marcoieni** [comment]
Thank you so much!

**Pull request merged**
