### PR TITLE
adding dash / quick docs and type defs

### PR DESCRIPTION
**Pull request by mangosmoothie**
Might be useful to those who use Dash - kept the same keybindings from the spacemacs dash layer.  QuickDef and TypeDef are not standard, though I find the bindings useful.

### CODE REVIEW

**Comment by marcoieni** [comment]
I like the idea to add `d` as docs :)

If `SPC d j` and `SPC d f` are invented by you they should go in [extra](https://github.com/MarcoIeni/intellimacs/tree/master/extra)/docs.vim

For `SPC d d` and `SPC d D` I have a problem: spacemacs uses zeal if you are on linux or windows. I don't think IdeaVim is able to handle logic like "if you are on mac map this, otherwise that". Therefore I don't like the idea to assign some key bindings to mac users only.

**Comment by mangosmoothie** [comment]
Just now looked at the plugin website it looks like the "Dash" plugin for Intellij actually supports Zeal & Velocity.

https://plugins.jetbrains.com/plugin/7351-dash/

Still seems the dependency matrix of 2 required prerequisites (plugin + backend doc server) may be a bit much for this so I'm ok with closing this out.

**Comment by marcoieni** [comment]
The QuickTypeDefinition action is nice. Maybe we could find a place for that.
I propose to put it with `<leader>mht` in [this](https://github.com/MarcoIeni/intellimacs/blob/master/major/help-hierarchy.vim) file where the `t` stands for type.
You used the `f`. What it stands for?

**Comment by marcoieni** [comment]
I added `<leader>mht` in d70d5d57fff1e40bc1f420607426a56f4475defc

**Pull request closed without merging**
